config/routes.rb
Rails.application.routes.draw do

	root 'pages#welcome'

	get 'about', to: 'pages#about'
	get 'images', to: 'pages#images'
	get 'trips', to: 'pages#trips'

	resources :database

	resources :peaks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/peak.rb
class Peak < ApplicationRecord

validates :altitude, presence: true
validates :prominence, presence: true
validates :isolation, presence: true
validates :key_col, presence: true
validates :source, presence: true
validates :accessibility, presence: true
validates :land_use, presence: true
validates :hazard, presence: true
validates :longitude, presence: true
validates :latitude, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/database_controller.rb
class DatabaseController < ApplicationController

	def show
		@peak = Peak.find(params[:id])
	end

	def index
		@peaks = Peak.all
	end

	def new
		@peak = Peak.new
	end

	def create
		@peak = Peak.new(peak_params)

		if @peak.save
			redirect_to @peak
		else
			render 'new'
		end
	end

	def destroy
	end

	private
		def peak_params
			params.require(:peak).permit(:name, :altitude, :prominence, :isolation, :key_col, :source, :accessibility, :land_use, :hazard, :longitude, :latitude)
		end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

	def show
	end

	def index
		
	end

	def new
		
	end

	def edit
		
	end

	def create
		
	end

	def delete
		
	end



end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/peaks_controller.rb
class PeaksController < ApplicationController
	
	def show
		@peak = Peak.find(params[:id])
	end

	def index
		@peaks = Peak.all
	end

	def new
		@peak = Peak.new
	end

	def create
		@peak = Peak.new(peak_params)

		if @peak.save
			redirect_to @peak
		else
			render 'new'
		end
	end

	def destroy
	end

	private
		def peak_params
			params.require(:peak).permit(:name, :altitude, :prominence, :isolation, :key_col, :source, :accessibility, :land_use, :hazard, :longitude, :latitude)
		end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

	def show
		
	end

	def index
		
	end

	def new
		
	end

	def edit
		
	end

	def create

	end

	def destroy
		
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/database_helper.rb
module DatabaseHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/database/index.html.erb
<strong>e ci s'ha i databaseee</strong>

app/views/database/new.html.erb
<h1> New data to insert</h1>

<%= form_with scope: :peak, url: peaks_path, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :altitude %><br>
    <%= form.text_area :altitude %>
  </p>

  <p>
    <%= form.label :prominence %><br>
    <%= form.text_area :prominence %>
  </p>  

  <p>
    <%= form.label :prominence %><br>
    <%= form.text_area :prominence %>
  </p>

    <p>
    <%= form.label :isolation %><br>
    <%= form.text_area :isolation %>
  </p>

    <p>
    <%= form.label :key_col %><br>
    <%= form.text_area :key_col %>
  </p>

    <p>
    <%= form.label :source %><br>
    <%= form.text_area :source %>
  </p>

    <p>
    <%= form.label :accessibility %><br>
    <%= form.text_area :accessibility %>
  </p>

  <p>
    <%= form.label :land_use %><br>
    <%= form.text_area :land_use %>
  </p>

    <p>
    <%= form.label :hazard %><br>
    <%= form.text_area :hazard %>
  </p>

    <p>
    <%= form.label :longitude %><br>
    <%= form.text_area :longitude %>
  </p>

    <p>
    <%= form.label :latitude %><br>
    <%= form.text_area :latitude %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/database/show.html.erb
<h1>I show here</h1>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light" id="navbar">
      <%= link_to "PICK YOUR PEAKS", root_path, class: "navbar-brand", id: "logo" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse " id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item rounded">
          <%= link_to "Map", '#', class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Trips", '#', class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href='#'> Action2 </a><a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <%= link_to "Forum", '#', class: "nav-link" %>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pickyourpeaks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1 id="big">SUCA ANCORA NON C'E' NULLA :D</h1>

app/views/pages/welcome.html.erb
<div id="main">
<div class="container-full-bg">  <!--  increased the jumbotron width -->
	<div class="jumbotron jumbotron-fluid">
		
		<div >
			<h1 class="align-middle">Welcome to Pick Your Peaks</h1>
			<h2>Here you can find an accurate data set of peaks </h2>
		</div>
	</div>
</div>



<div  class="mid-txt">
	
<p>Pick your Peaks è un progetto indipendente che nasce nell’Aprile del 2020 dalla grande passione per l’escursionismo, la geografia ed in particolar modo la cartografia. L’orografia è quella parte della geografia fisica che studia e descrive le caratteristiche dei rilievi montuosi. In essa rientrano le vette, nelle sue numerose denominazioni. Il primo obiettivo di questo progetto è costruire un database esaustivo delle vette presenti sul territorio, includendo anche i rilievi minori, con una prominenza minima di 5 metri, spesso non riportati sulle carte o su altre fonti disponibili su internet od altrove.
Il secondo obiettivo è che questo database possa essere utile e d’interesse a tutti coloro che, come me, coltivano la passione per le vette in senso ampio (in montagna, in collina o anche su un isolotto) e la propensione a raggiungerle, come traguardi piccoli o grandi della propria esistenza.</p>

</div>




  <%= image_tag "Appenines - Mount Falterona.jpg", :width => '100%', :height => '250px' %>

app/views/peaks/index.html.erb
<strong>diahaneeeeeeee</strong>

app/views/peaks/new.html.erb
<h1> New data to insert</h1>

<%= form_with scope: :peak, url: peaks_path, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :altitude %><br>
    <%= form.text_area :altitude %>
  </p>

  <p>
    <%= form.label :prominence %><br>
    <%= form.text_area :prominence %>
  </p>  

  <p>
    <%= form.label :prominence %><br>
    <%= form.text_area :prominence %>
  </p>

    <p>
    <%= form.label :isolation %><br>
    <%= form.text_area :isolation %>
  </p>

    <p>
    <%= form.label :key_col %><br>
    <%= form.text_area :key_col %>
  </p>

    <p>
    <%= form.label :source %><br>
    <%= form.text_area :source %>
  </p>

    <p>
    <%= form.label :accessibility %><br>
    <%= form.text_area :accessibility %>
  </p>

  <p>
    <%= form.label :land_use %><br>
    <%= form.text_area :land_use %>
  </p>

    <p>
    <%= form.label :hazard %><br>
    <%= form.text_area :hazard %>
  </p>

    <p>
    <%= form.label :longitude %><br>
    <%= form.text_area :longitude %>
  </p>

    <p>
    <%= form.label :latitude %><br>
    <%= form.text_area :latitude %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>